name: 'Test stringi'
'on':
  push:
    branch: master
  schedule:
    - cron:  '0 10 * * *'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://packagemanager.rstudio.com/all/329')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://packagemanager.rstudio.com/all/329')"
      - name: 'Try to use stringr'
        run: |-
          Rscript -e "library(stringr); str_c('Letter: ', letters)"
