name: 'Test stringi'
'on':
  push:
    branch: master
  schedule:
    - cron:  '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes')"
          Rscript -e "install.packages('stringi')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: 'Try to use stringr'
        run: |-
          Rscript -e "library(stringr); str_c("Letter: ", letters)"
    container: rocker/verse:latest
